# Generated by Django 5.1.7 on 2026-01-17 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportedQuestion',
            fields=[
            ],
            options={
                'verbose_name': 'Reported Question',
                'verbose_name_plural': 'Reported Questions',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('questions.question',),
        ),
    ]
