# Generated by Django 5.1.7 on 2026-01-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_reportedquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_reported',
            field=models.BooleanField(default=False),
        ),
    ]
